[package]
name = "leptos-use"
version = "0.10.9"
edition = "2021"
authors = ["Marc-Stefan Cassola"]
categories = ["gui", "web-programming"]
description = "Collection of essential Leptos utilities inspired by SolidJS USE / VueUse"
exclude = ["examples/", "tests/"]
keywords = ["leptos", "utilities"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/Synphonyte/leptos-use"
homepage = "https://leptos-use.rs"

[dependencies]
actix-web = { version = "4", optional = true, default-features = false }
async-trait = "0.1"
base64 = { version = "0.21", optional = true }
cfg-if = "1"
cookie = { version = "0.18", features = ["percent-encode"] }
default-struct-builder = "0.5"
futures-util = "0.3"
gloo-timers = { version = "0.3", features = ["futures"] }
gloo-utils = { version = "0.2" }
http1 = { version = "1", optional = true, package = "http" }
http0_2 = { version = "0.2", optional = true, package = "http" }
js-sys = "0.3"
lazy_static = "1"
leptos = { version = "0.7.0-preview2" }
leptos_axum = { version = "0.7.0-preview2", optional = true }
leptos_actix = { version = "0.6", optional = true }
leptos-spin = { version = "0.2", optional = true }
num = { version = "0.4", optional = true }
paste = "1"
prost = { version = "0.12", optional = true }
rmp-serde = { version = "1.1", optional = true }
serde = { version = "1", optional = true }
serde_json = { version = "1", optional = true }
thiserror = "1"
wasm-bindgen = "0.2.92"
wasm-bindgen-futures = "0.4"

[dependencies.web-sys]
version = "0.3"
features = [
    "AddEventListenerOptions",
    "BinaryType",
    "BroadcastChannel",
    "Coordinates",
    "Clipboard",
    "CloseEvent",
    "CssStyleDeclaration",
    "CustomEvent",
    "CustomEventInit",
    "DisplayMediaStreamConstraints",
    "DomRect",
    "DomRectReadOnly",
    "DataTransfer",
    "DragEvent",
    "Element",
    "EventListener",
    "EventListenerOptions",
    "EventSource",
    "EventSourceInit",
    "EventTarget",
    "File",
    "FileList",
    "Geolocation",
    "HtmlDocument",
    "HtmlElement",
    "HtmlLinkElement",
    "HtmlStyleElement",
    "IntersectionObserver",
    "IntersectionObserverInit",
    "IntersectionObserverEntry",
    "Location",
    "MediaDevices",
    "MediaQueryList",
    "MediaStream",
    "MediaStreamTrack",
    "MessageEvent",
    "MouseEvent",
    "MutationObserver",
    "MutationObserverInit",
    "MutationRecord",
    "Navigator",
    "NodeList",
    "Notification",
    "NotificationDirection",
    "NotificationOptions",
    "NotificationPermission",
    "Permissions",
    "PermissionState",
    "PermissionStatus",
    "PointerEvent",
    "Position",
    "PositionError",
    "PositionOptions",
    "ReadableStream",
    "ReadableStreamDefaultReader",
    "ReadableStreamGetReaderOptions",
    "ReadableStreamReaderMode",
    "ResizeObserver",
    "ResizeObserverBoxOptions",
    "ResizeObserverEntry",
    "ResizeObserverOptions",
    "ResizeObserverSize",
    "ScrollBehavior",
    "ScrollToOptions",
    "ServiceWorker",
    "ServiceWorkerContainer",
    "ServiceWorkerRegistration",
    "ServiceWorkerState",
    "Storage",
    "StorageEvent",
    "Touch",
    "TouchEvent",
    "TouchList",
    "Url",
    "UrlSearchParams",
    "VisibilityState",
    "WebSocket",
    "WebTransport",
    "WebTransportOptions",
    "WebTransportDatagramDuplexStream",
    "WebTransportBidirectionalStream",
    "Window",
    "WebTransportReceiveStream",
    "WebTransportSendStream",
    "WritableStream",
    "WritableStreamDefaultWriter",
]

[dev-dependencies]
getrandom = { version = "0.2", features = ["js"] }
leptos_meta = "0.7.0-preview2"
rand = "0.8"

[features]
actix = ["dep:actix-web", "dep:leptos_actix", "dep:http0_2"]
axum = ["dep:leptos_axum", "dep:http1"]
docs = []
math = ["num"]
prost = ["base64", "dep:prost"]
serde = ["dep:serde", "serde_json"]
spin = ["dep:leptos-spin", "dep:http1"]
ssr = []
msgpack = ["dep:rmp-serde", "dep:serde"]

[package.metadata.docs.rs]
features = ["math", "docs", "ssr", "prost", "serde"]
